install / initialise rvm as required

diff --git a/bashrc.d/rvm b/bashrc.d/rvm
--- a/bashrc.d/rvm
+++ b/bashrc.d/rvm
@@ -1,4 +1,14 @@
 function bashrc.d_rvm_init(){
-	[ -d "$HOME/.rvm/bin" ] && PATH="$PATH:$HOME/.rvm/bin"
-	[ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm"
+	if [[ ! -s "$HOME/.rvm/scripts/rvm" ]]; then
+		gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
+		curl -sSL https://get.rvm.io | bash -s stable --ruby
+	fi
+
+	if [[ ! -s "$HOME/.rvm/scripts/rvm" ]]; then
+		echo "RVM could not be initialised" >&2
+		return 1
+	fi
+
+	[[ -d "$HOME/.rvm/bin" ]] && PATH="$PATH:$HOME/.rvm/bin"
+	. "$HOME/.rvm/scripts/rvm"
 }
